{{- include "require" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elixier.fullname" . }}-presto-catalogs
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
type: Opaque
stringData:
  default.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri={{ include "elixier.hive.metastore_uri" . }}
    hive.s3.path-style-access=true
    hive.s3.endpoint={{ .Values.s3a.endpoint }}
    hive.s3.aws-access-key={{ .Values.s3a.access_key }}
    hive.s3.aws-secret-key={{ .Values.s3a.secret_key }}
    hive.non-managed-table-writes-enabled=true
    hive.storage-format=parquet

