apiVersion: v1
kind: Service
metadata:
  name: {{ include "elixier.fullname" . }}-hue
  labels:
    {{- include "elixier.labels" . | nindent 4 }}
    component: hue
    subcomponent: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elixier.selectorLabels" . | nindent 4 }}
    component: hue
    subcomponent: web

